# Generated by Django 5.2.6 on 2025-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, help_text='Источник (например, фильм или книга)', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Вес цитаты (чем выше, тем больше шанс отображения)'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('text', 'author', 'source'), name='unique_quote'),
        ),
    ]
