# Generated by Django 5.2.6 on 2025-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_dislikes_quote_likes_quote_source_quote_views_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quote',
            name='unique_quote',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Источник (фильм/книга)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True, verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес'),
        ),
    ]
